import type { GameLevel } from './game-store';

export interface Language {
  id: string;
  name: string;
  flag: string;
  color: string;
  isUnlocked: boolean;
}

export const AVAILABLE_LANGUAGES: Language[] = [
  {
    id: 'english',
    name: 'English',
    flag: '🇿🇦',
    color: '#1976d2',
    isUnlocked: true,
  },
  {
    id: 'sepedi',
    name: 'Sepedi',
    flag: '🇿🇦',
    color: '#d32f2f',
    isUnlocked: true,
  },
  {
    id: 'xitsonga',
    name: 'Xitsonga',
    flag: '🇿🇦',
    color: '#388e3c',
    isUnlocked: true,
  },
  {
    id: 'tswana',
    name: 'Setswana',
    flag: '🇿🇦',
    color: '#ff9800',
    isUnlocked: true,
  },
  {
    id: 'zulu',
    name: 'isiZulu',
    flag: '🇿🇦',
    color: '#9c27b0',
    isUnlocked: true,
  },
];

export const GAME_LEVELS: Record<string, GameLevel[]> = {
  english: [
    {
      id: 1,
      name: 'Cape Town - Table Mountain',
      letters: ['C', 'A', 'T', 'R'],
      crosswordGrid: [],
      targetWords: ['CAT', 'CART', 'ART', 'RAT'],
      isUnlocked: true,
      isCompleted: false,
      stars: 0,
      landmark: 'pyramid.jpg',
      language: 'english',
    },
    {
      id: 2,
      name: 'Johannesburg - Gold Reef City',
      letters: ['L', 'O', 'V', 'E', 'R'],
      crosswordGrid: [],
      targetWords: ['LOVE', 'ORE', 'LOVER', 'OVER'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'eiffel.jpg',
      language: 'english',
    },
    {
      id: 3,
      name: 'Durban - Golden Mile',
      letters: ['S', 'U', 'N', 'M', 'O', 'R'],
      crosswordGrid: [],
      targetWords: ['SUN', 'WORN', 'MOURN', 'NORM'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'colosseum.jpg',
      language: 'english',
    },
    {
      id: 4,
      name: 'Pretoria - Union Buildings',
      letters: ['F', 'L', 'O', 'W', 'E', 'R'],
      crosswordGrid: [],
      targetWords: ['FLOW', 'FLOWER', 'LOWER', 'OWL'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'fuji.jpg',
      language: 'english',
    },
    {
      id: 5,
      name: 'Bloemfontein - Naval Hill',
      letters: ['M', 'A', 'G', 'I', 'C', 'K'],
      crosswordGrid: [],
      targetWords: ['MAGIC', 'MICK', 'GAMIC', 'KICK'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'taj.jpg',
      language: 'english',
    },
    {
      id: 6,
      name: 'Port Elizabeth - Beachfront',
      letters: ['S', 'T', 'A', 'R', 'T'],
      crosswordGrid: [],
      targetWords: ['START', 'STAR', 'ART', 'TAR'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'arc.jpg',
      language: 'english',
    },
    {
      id: 7,
      name: 'Kimberley - Big Hole',
      letters: ['H', 'E', 'A', 'R', 'T'],
      crosswordGrid: [],
      targetWords: ['HEART', 'HEAR', 'TEAR', 'RATE'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'brandenburg.jpg',
      language: 'english',
    },
    {
      id: 8,
      name: 'Nelspruit - Kruger Park',
      letters: ['G', 'R', 'E', 'A', 'T'],
      crosswordGrid: [],
      targetWords: ['GREAT', 'GEAR', 'TEAR', 'RATE'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'pisa.jpg',
      language: 'english',
    },
    {
      id: 9,
      name: 'East London - Orient Beach',
      letters: ['W', 'O', 'R', 'L', 'D'],
      crosswordGrid: [],
      targetWords: ['WORLD', 'WORD', 'LORD', 'OLD'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'christ.jpg',
      language: 'english',
    },
    {
      id: 10,
      name: 'Polokwane - Game Reserve',
      letters: ['P', 'E', 'A', 'C', 'E'],
      crosswordGrid: [],
      targetWords: ['PEACE', 'PACE', 'CAPE', 'ACE'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'sagrada.jpg',
      language: 'english',
    },
  ],
  sepedi: [
    {
      id: 1,
      name: 'Polokwane - Limpopo Province',
      letters: ['L', 'E', 'R', 'A', 'T', 'O'],
      crosswordGrid: [],
      targetWords: ['LERATO', 'RATO', 'TORE'],
      isUnlocked: true,
      isCompleted: false,
      stars: 0,
      landmark: 'sagrada.jpg',
      language: 'sepedi',
    },
    {
      id: 2,
      name: 'Tzaneen - Magoebaskloof',
      letters: ['T', 'H', 'A', 'B', 'O'],
      crosswordGrid: [],
      targetWords: ['THABO', 'BATH', 'BOAT'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'chichen.jpg',
      language: 'sepedi',
    },
    {
      id: 3,
      name: 'Mokopane - Waterberg',
      letters: ['K', 'A', 'G', 'I', 'S', 'O'],
      crosswordGrid: [],
      targetWords: ['KAGISO', 'KAGO', 'SOAK'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'fuji.jpg',
      language: 'sepedi',
    },
  ],
  xitsonga: [
    {
      id: 1,
      name: 'Giyani - Limpopo Valley',
      letters: ['R', 'I', 'R', 'A', 'N', 'D', 'Z', 'U'],
      crosswordGrid: [],
      targetWords: ['RIRANDZU', 'RANDU', 'RAND'],
      isUnlocked: true,
      isCompleted: false,
      stars: 0,
      landmark: 'arc.jpg',
      language: 'xitsonga',
    },
    {
      id: 2,
      name: 'Malamulele - Kruger Border',
      letters: ['V', 'U', 'T', 'O', 'M', 'I'],
      crosswordGrid: [],
      targetWords: ['VUTOMI', 'TOMI', 'VUTO'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'brandenburg.jpg',
      language: 'xitsonga',
    },
    {
      id: 3,
      name: 'Hoedspruit - Blyde River',
      letters: ['N', 'S', 'A', 'T', 'I'],
      crosswordGrid: [],
      targetWords: ['NSATI', 'SATIN', 'SAINT'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'taj.jpg',
      language: 'xitsonga',
    },
  ],
  tswana: [
    {
      id: 1,
      name: 'Mafikeng - North West Province',
      letters: ['L', 'O', 'R', 'A', 'T', 'O'],
      crosswordGrid: [],
      targetWords: ['LORATO', 'LORA', 'TARO'],
      isUnlocked: true,
      isCompleted: false,
      stars: 0,
      landmark: 'pisa.jpg',
      language: 'tswana',
    },
    {
      id: 2,
      name: 'Rustenburg - Pilanesberg',
      letters: ['T', 'U', 'M', 'E', 'L', 'O'],
      crosswordGrid: [],
      targetWords: ['TUMELO', 'MELO', 'LUTE'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'christ.jpg',
      language: 'tswana',
    },
    {
      id: 3,
      name: 'Potchefstroom - Mooi River',
      letters: ['K', 'A', 'G', 'I', 'S', 'O'],
      crosswordGrid: [],
      targetWords: ['KAGISO', 'KAGO', 'SOAK'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'colosseum.jpg',
      language: 'tswana',
    },
  ],
  zulu: [
    {
      id: 1,
      name: 'KwaZulu-Natal - Drakensberg',
      letters: ['U', 'T', 'H', 'A', 'N', 'D', 'O'],
      crosswordGrid: [],
      targetWords: ['UTHANDO', 'THANDO', 'HANDO'],
      isUnlocked: true,
      isCompleted: false,
      stars: 0,
      landmark: 'arc.jpg',
      language: 'zulu',
    },
    {
      id: 2,
      name: 'Hluhluwe - Game Reserve',
      letters: ['U', 'B', 'U', 'N', 'T', 'U'],
      crosswordGrid: [],
      targetWords: ['UBUNTU', 'BUNT', 'TUN'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'brandenburg.jpg',
      language: 'zulu',
    },
    {
      id: 3,
      name: 'Pietermaritzburg - Capital City',
      letters: ['I', 'N', 'K', 'O', 'S', 'I'],
      crosswordGrid: [],
      targetWords: ['INKOSI', 'KOSI', 'SIN'],
      isUnlocked: false,
      isCompleted: false,
      stars: 0,
      landmark: 'christ.jpg',
      language: 'zulu',
    },
  ],
};

export const getLevel = (language: string, id: number): GameLevel | undefined => {
  return GAME_LEVELS[language]?.find((level) => level.id === id);
};

export const getUnlockedLevels = (language: string, completedLevels: number[]): GameLevel[] => {
  const levels = GAME_LEVELS[language] || [];
  return levels.map((level) => ({
    ...level,
    isUnlocked: level.id === 1 || completedLevels.includes(level.id - 1),
    isCompleted: completedLevels.includes(level.id),
  }));
};

export const getUnlockedLanguages = (): Language[] => {
  return AVAILABLE_LANGUAGES.map((lang) => ({
    ...lang,
    isUnlocked: true,
  }));
};
